version: '3.9'

services:
  otel-collector:
    extends:
      file: docker-compose.base.yml
      service: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"

  jaeger:
    extends:
      file: docker-compose.base.yml
      service: jaeger
    ports:
      - "16686:16686"
      - "14250:14250"

  prometheus:
    extends:
      file: docker-compose.base.yml
      service: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    extends:
      file: docker-compose.base.yml
      service: grafana
    ports:
      - "3400:3000"

volumes:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-dotmac}-observability
